default: &default
  host: localhost
  port: 5432
  username: postgres
  password: 12345678
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: contacts_system_dev

test:
  <<: *default
  database: contacts_system_test

production:
  <<: *default
  database: contacts_system_prod
