version: '3.8'
services:
  fullcomerce-1:
    container_name: "fullcomerce-1"
    build: ./
    image: fullcomerce-1:latest
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      - "5000:80"
      - "5001:3306"
    expose:
      - "80"
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./apps:/apps