version: '3.8'
services:
  fullcommerce-1:
    container_name: "fullcommerce-1"
    build: ./
    image: fullcommerce-1:latest
    env_file:
    - fullcommerce-1.env
    ports:
      - "5000:80"
      - "5001:3306"
    expose:
      - "80"
      - "3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./fullcommerce:/fullcommerce