version: '3.8'
services:
  fullcommerce_1-mysql:
    container_name: "fullcommerce_1-mysql"
    image: mysql:5.7.30
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3001:3306"
    expose:
      - 3306
    volumes:
      - ./fullcommerce/databases/mysql/server:/var/lib/mysql