version: '3.8'
services:
  fullcommerce_1-mysql:
    container_name: "fullcommerce_1-mysql"
    image: mysql:5.7.30
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3001:3306"
    expose:
      - 3306
    volumes:
      - ./fullcommerce/store/databases/mysql/server:/var/lib/mysql
  fullcommerce_1-store_api:
    container_name: "fullcommerce_1-store_api"
    build: ./fullcommerce/store/api
    image: fullcommerce_1-store_api
    ports:
      - "3000:80"
    command: npm run dev
    # command: npm start
    expose:
      - 80
    volumes:
      - ./fullcommerce/store/api:/api