version: '3.8'
services:
    mysqlsrv:
        image: mysql:5.7.30
        environment:
            MYSQL_ROOT_PASSWORD: "12345678"
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - ./database/mysql/server:/var/lib/mysql
    # store:
    #     image: node:10.17.0
    #     ports:
    #         - "80:80"
    #     expose:
    #         - "80"
    #     volumes:
    #         - ./store:/store