version: '3.8'
services:
  local-golang:
    container_name: local-golang
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: local-golang:latest
    command: 'sh docker/command.sh'
    volumes:
      - .:/local-golang
